### ISSUE TITLE
FR: update existing request logs after the request is finished

### ISSUE THREAD

**Issue by comes** [bilfeldt/laravel-request-logger#26]
As far as I can read from the source, this package handles a request and creates a new request_logs entry whenever a request cycle is done.
That might be something that I, as a SysOps, would not expect.
I expect to log the incoming request as early as possible. Log the incoming IP, request, client request ID, whatever... then handle the request by the framework and afterward update the existing request log with the response data, memory usage, and duration.

The reason why I'm pointing this out here is whenever a request comes in and, for whatever reason, the PHP process dies in the middle of the request, it will never be logged. Whenever something happens that the framework cannot control, I will never find a log entry. Isn't it?

Greetings, J

**Comment by bilfeldt** [comment]
That is completely right - and by intention to avoid every request being slowed down with a database query before the response was returned.

I think the current implementation should still be the default since it works for the majority of cases yet it does not impact performance.

It is easy implementing your middleware that does the logging in two steps, but I would be open for adding a config in this package to do it.

But as you say we can do a pre-save of the request info and then once the response is returned update it with the response fields (we can use the uuid which is unique and known). This will impact performance. An alternative would be using jobs 🧐 there is already a setting for that, so if that is enabled, maybe that should be the way to go.

**Comment by comes** [comment]
https://laravel.com/docs/10.x/middleware#terminable-middleware would not have any additional impact. you will have a write operation to the database -> executing the request cycle of routes and everything -> send response -> call terminable middleware and update existing log.

if you go for a job, you need to take care, that something is already in the database and you need to take care of the correct order. you should not write the response log before the incoming request log.

**Comment by bilfeldt** [comment]
We can use either _terminable middleware_ or listen for the `Illuminate\Foundation\Http\Events\RequestHandled` event (current implementation). Both approaches mean that any work done there will not affect the response time seen by the customers because the response has already been returned.

*But* any work done before, like saving the request parameters to db, will ensure a delay on every single response, which should not be the default behavior of this package.

We *could* make an opt-in setting whether or not a "pre save" should be done. The final logging could then be performed using an `updateOrCreate` operation. But this would be a major breaking change because it does not conform with the interface: https://github.com/bilfeldt/laravel-request-logger/blob/main/src/Contracts/RequestLoggerInterface.php

I am closing this for now because:
1. Such an implementation would be a major breaking change
2. This is already possible by implementing your own middleware that pre-logs and then update the saving logic to be updateOrCreate: https://github.com/bilfeldt/laravel-request-logger/blob/95dfd9c0db7421926e0c1a77c09615acea907eec/src/Models/RequestLog.php#L124
